### PR TITLE
Bidding token errors

### LINKED ISSUE #17: Validate the form when Auctioning and Bidding tokens are filled in with the same address
To prevent a user against of creation 'invalid' auction, it would be nice to validate the form when Auctioning and Bidding tokens are filled in with the same address (add a warning + keep 'Build transaction' button disabled)

### LINKED ISSUE #19: Validation message is not displayed for required fields
Validation message is not displayed for the next required fields when they are empty:
 - Bidding token
 -  Auction end time
 - Auction cancel date time
empty

**Expected**: 'Field required' validation message should be displayed when fields are empty.

In addition, there is no validation message for the 'Bidding token' field when it is filled in with an incorrectly formatted address invalid address

Expected: 'Invalid address' validation message should be displayed

### LINKED ISSUE #21: No validation when required amounts fields are filled in with 0
The issue is related to the next fields: 
 - number of tokens to auction off
 - number of tokens to buy
 - min funding for execution 
image

When I run such a transaction, it will fail (as it fails in the etherscan). 

image

Hence, it would be great to keep 'Build transaction' disabled when these fields are filled in with 0
and to add a validation message (value should be > 0), 
OR change a placeholder to 0.01 or so

### LINKED ISSUE #30: Biddint Token wrong address not recognized as wrong
While the Auctioning token field parameter does prompt a message of Invalid address whenever the address is incorrect, the bidding token field parameter does not do that but it should. 
Screenshot 2021-03-25 at 12 55 42

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #21 
Closes #17 
Closes #30 
Closes #19

This refactor a lot, it should be more smooth in performance ~~but **without messages about Invalid ERC20 or Not enough balance BEFORE submit**, that is the reason that this is a draft. It doesn't mean to be a better version but for sure~~ should be less buggy.

### CODE REVIEW

**Comment by josojo** [comment]
Cool. let's merge after the customer test

**Comment by elena-zh** [comment]
Hi Maxi!
Now the app is not crashed when I fill in an address that is not an ERC20 + validation messages on format and emptiness of the field appear.  However, here are my issues: 
1. Pop-up to sign transaction appears when amount>balance


2. Validation message appears after pressing on the 'Build transaction' button when an address is not valid. So it will be difficult to understand what is wrong with the transaction: 


Could you please take a look at these issues?

**Comment by josojo** [comment]
Nit: 
image
a value of 0 is perfectly fine :)

**Review by josojo — APPROVED** [review]
good refactor :)

**Comment by elena-zh** [comment]
Hi @hpmaxi !
Great job!
#17 is fixed
#19 is almost fixed, however, the app is crashed when I clear out date fields (#32)
#30 is fixed
#21 is almost fixed, however, sometimes validation messages are not displayed on the FE side. I have created an issue for this case: #33

**Pull request merged**
